kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lucit-ubdcc-pve
  namespace: lucit-ubdcc
  labels:
    app: lucit-ubdcc-mgmt
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi