apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.restapi }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name.restapi }}
  ports:
    - name: http
      port: {{ .Values.publicPort.restapi }}
      targetPort: 8080
  type: LoadBalancer
