apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: lucit-ubdcc-restapi
  namespace: lucit-ubdcc
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: lucit-ubdcc-restapi
  replicas: 3
  selector:
    matchLabels:
      app: lucit-ubdcc-restapi
  template:
    metadata:
      labels:
        app: lucit-ubdcc-restapi
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: lucit-ubdcc-restapi
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: lucit-ubdcc-restapi
          image: i018oau9.c1.de1.container-registry.ovh.net/library/lucit-ubdcc-restapi@sha256:16f2b8172ceb916bfea223cb863344500b5bc44495ab074ac18645dd7fa53729
          ports:
            - name: rest-private
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /test
              port: rest-private
            initialDelaySeconds: 40
          livenessProbe:
            httpGet:
              path: /test
              port: rest-private
            initialDelaySeconds: 40
