apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.mgmt }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.name.mgmt }}
  ports:
    - name: http
      port: 4280
      targetPort: 8080
  type: NodePort
