apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.name.mgmt }}
  namespace: {{ .Release.Namespace }}
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: {{ .Values.name.mgmt }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name.mgmt }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name.mgmt }}
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      containers:
        - name: {{ .Values.name.mgmt }}
          image: "i018oau9.c1.de1.container-registry.ovh.net/library/lucit-ubdcc-mgmt:{{ .Chart.AppVersion }}"
          ports:
            - name: rest-private
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
