apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: "lucit-lucit-lucit-ubdcc-mgmt"
  replicas: 1
  selector:
    matchLabels:
      app: lucit-ubdcc-mgmt
  template:
    metadata:
      labels:
        app: lucit-ubdcc-mgmt
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      containers:
        - name: lucit-lucit-lucit-ubdcc-mgmt
          image: i018oau9.c1.de1.container-registry.ovh.net/library/lucit-lucit-lucit-ubdcc-mgmt@sha256:5ee4dd9f547e09e8f1ca9c22a1816009b79c9ab9e8ef3ded321d40a6b07bdcb2
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
          volumeMounts:
            - name: lucit-ubdcc-pve
              mountPath: /app/logs
      volumes:
        - name: lucit-ubdcc-pve
          persistentVolumeClaim:
            claimName: lucit-ubdcc-pve
