apiVersion: v1
kind: Service
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
spec:
  selector:
    app: lucit-ubdcc-mgmt
  ports:
    - name: http
      port: 4280
      targetPort: rest-private
  type: ClusterIP
