apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: "generic_loader"
  replicas: 1
  selector:
    matchLabels:
      app: lucit-ubdcc-mgmt
  template:
    metadata:
      labels:
        app: lucit-ubdcc-mgmt
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      containers:
        - name: generic_loader
          image: i018oau9.c1.de1.container-registry.ovh.net/library/generic_loader@sha256:9a44812f88bb4a5e5a9c512153253353928194df6aef303a96ebfac8476bec38
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
