apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: "lucit-ubdcc-mgmt"
  replicas: 1
  selector:
    matchLabels:
      app: lucit-ubdcc-mgmt
  template:
    metadata:
      labels:
        app: lucit-ubdcc-mgmt
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      containers:
        - name: lucit-ubdcc-mgmt
          image: i018oau9.c1.de1.container-registry.ovh.net/library/lucit-ubdcc-mgmt@sha256:fa3486e258f341c8060a89a3bded0ad2ac65a9e26dee2e8e38aa719d1024be82
          ports:
            - name: rest-private
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
