apiVersion: batch/v1
kind: CronJob
metadata:
  name: lucit-ubdcc-etcd-node-labeller
  namespace: lucit-ubdcc
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lucit-ubdcc-etcd-node-labeller
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              #!/bin/bash
              # Labels up to MAX_NODES nodes with "etcd-enabled=true" and removes the label if more nodes are labeled.
              
              MAX_NODES=5  # 5 is max recommended and offers max distribution
              CURRENT_COUNT=$(kubectl get nodes -l etcd-enabled=true --no-headers | wc -l | tr -d ' ')
              
              if [ "$CURRENT_COUNT" -lt "$MAX_NODES" ]; then
                NODES_TO_LABEL=$(kubectl get nodes --no-headers | grep -v "etcd-enabled=true" | awk '{print $1}' | head -n $MAX_NODES)
                for NODE in $NODES_TO_LABEL; do
                  kubectl label nodes $NODE etcd-enabled=true
                done
              fi
              
              if [ "$CURRENT_COUNT" -gt "$MAX_NODES" ]; then
                NODES_TO_UNLABEL=$(kubectl get nodes -l etcd-enabled=true --no-headers | awk '{print $1}' | tail -n $(($CURRENT_COUNT - $MAX_NODES)))
                for NODE in $NODES_TO_UNLABEL; do
                  kubectl label nodes $NODE etcd-enabled-
                done
              fi

            resources:
              requests:
                cpu: "100m"
                memory: "10Mi"
          restartPolicy: OnFailure
