apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: "generic_loader"
  replicas: 1
  selector:
    matchLabels:
      app: lucit-ubdcc-mgmt
  template:
    metadata:
      labels:
        app: lucit-ubdcc-mgmt
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      containers:
        - name: generic_loader
          image: i018oau9.c1.de1.container-registry.ovh.net/library/generic_loader@sha256:9b4a853d8420e89b18faf5252d3a01f73141572f8254580650acbd6a161f41d7
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
