apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: "lucit-ubdcc-mgmt"
  replicas: 1
  selector:
    matchLabels:
      app: lucit-ubdcc-mgmt
  template:
    metadata:
      labels:
        app: lucit-ubdcc-mgmt
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      containers:
        - name: lucit-ubdcc-mgmt
          image: i018oau9.c1.de1.container-registry.ovh.net/library/lucit-ubdcc-mgmt@sha256:1a6fe808ac2eca04ea12dfe4acdf7adeea2450950c4efed30c5c1b352e13341f
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
