apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
  annotations:
    author: LUCIT <it@lucit.tech>
spec:
  serviceName: "lucit-ubdcc-mgmt"
  replicas: 1
  selector:
    matchLabels:
      app: lucit-ubdcc-mgmt
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: lucit-ubdcc-mgmt
      annotations:
        author: LUCIT <it@lucit.tech>
    spec:
      containers:
        - name: lucit-ubdcc-mgmt
          image: i018oau9.c1.de1.container-registry.ovh.net/library/lucit-ubdcc-mgmt@sha256:911870c2ef06402c5173cba9c9655e7c437a3c75339bc24a7dcdad185c58e5f0
          ports:
            - name: rest-private
              containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
