apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: lucit-ubdcc
subjects:
- kind: ServiceAccount
  name: default
  namespace: lucit-ubdcc
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io