name: Build and Publish GH+PyPi (lucit-ubdcc-mgmt)

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  build_wheels:
    name: Build Linux wheels for Python 3.12
    runs-on: ubuntu-20.04
    env:
      CIBW_BUILD: "cp312-*"
      CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-* pp36-* pp37-* pp38-* pp39-* pp310-* pp311-*"
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v4

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Check Python version
        run: python --version

      - name: Build wheels for Linux (Python 3.12)
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_BEFORE_ALL: "bash dev/tools/github/install_rust.sh"
          CIBW_SKIP: "cp36-* cp37-* cp38-* cp39-* cp310-* cp311-* pp36-* pp37-* pp38-* pp39-* pp310-* pp311-*"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  Release:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      discussions: write
      id-token: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Please read the [CHANGELOG](https://unicorn-binance-depthcache-cluster.docs.lucit.tech/changelog.html) for further information.
          discussion_category_name: releases
          draft: false
          files: | 
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true
          name: lucit-ubdcc-mgmt
          prerelease: false
          tag_name: 0.0.5
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PyPi Release
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
