apiVersion: v1
kind: Service
metadata:
  name: lucit-ubdcc-mgmt
  namespace: lucit-ubdcc
spec:
  selector:
    app: lucit-ubdcc-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  clusterIP: None
