apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lucit-ubdcc-dcn
  namespace: lucit-ubdcc
spec:
  selector:
    matchLabels:
      app: lucit-ubdcc-dcn
  template:
    metadata:
      labels:
        app: lucit-ubdcc-dcn
    spec:
      containers:
        - name: example-container
          image: i018oau9.c1.de1.container-registry.ovh.net/library/lucit-ubdcc-dcn@sha256:892a3a7e25c3ba86c54744006bffd6a73079629e19d5bc8f2ddebd1c3c13cebf
