apiVersion: v1
kind: Service
metadata:
  name: lucit-ubdcc-restapi
  namespace: lucit-ubdcc
spec:
  selector:
    app: lucit-ubdcc-restapi
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
